### ISSUE TITLE
Screensize used as base for the eyegaze plot

### ISSUE THREAD

**Issue by DouweHorsthuis** [uzh/edf-converter#10]
Hi, I was hoping one of you could help/clear this up for me. If I understand it correctly the eyegaze plot is created by taking the 0-max(posY) and 0-Max(posX). Which makes me think, why is the screen size/resolution of the screen the person is looking at not taking in consideration if this is availible? 

Using the Eyelink1000, we always send a message with the screen height/width in pixels to each EDF file. Can this somehow be intergrated in the plot? It seems to me now that the gaze plot is often "off" to one side or the other. I've attached 2 edf files, where the screen coordinates are in them (edf1.Events.Messages.info ). 
[EDFfiles.zip](https://github.com/uzh/edf-converter/files/11966588/EDFfiles.zip)

I really hope you can help me with this, thanks in advanced

**Comment by DouweHorsthuis** [comment]
To make it possibly work for me, in a way that it should work for different screen sizes. I added a loop that looks for the message. 

` %finding screen size  

    for i = 1:length(edf_temp.RawEdf.FEVENT)
        if  contains(edf_temp.RawEdf.FEVENT(i).codestring, 'MESSAGEEVENT') %else it'll break on non-strings
        if  contains(edf_temp.RawEdf.FEVENT(i).message, 'DISPLAY_COORDS') %looks for the screen resolution
            display_coords= str2num(edf_temp.RawEdf.FEVENT(i).message(end-9:end));
        end
        end
    end `

Like this I have the variable `display_coords` that contains the height and width of the screen as measured by the presenting software (presentation in our case). 
 
Then all the gazedata cannot be outside of this, even if it was measured as being outside of the screen. 

` %finding all the gaze points outsized of the screen size and deleting them  

for i = 1:size(gazedata, 1)  
        if   gazedata(i, 1) < 0 || gazedata(i, 2) < 0  
            gazedata(i, :) = [NaN, NaN];  
        elseif gazedata(i, :) > [display_coords(2),display_coords(1)]  
            gazedata(i, :) = [NaN, NaN];  
        elseif gazedata(i, 1) > [display_coords(2)]  
            gazedata(i, :) = [NaN, NaN];  
        elseif gazedata(i, 2) > [display_coords(1)]  
             gazedata(i, :) = [NaN, NaN];  
        end  
    end  
    gazedata = gazedata(~isnan(gazedata(:, 1)), :);`  

The only change that is now required is that the plotrange is incorrect. This should be `plotRange=[0 display_coords(1) 0 display_coords(2)];`

**Comment by DouweHorsthuis** [comment]
I wonder if this sounds sensible.

**Comment by mabiede** [comment]
@DouweHorsthuis, thanks for your suggestion, and sorry for the very long response time.

The current plot doesn't delete or change the "gaze values" (on purpose). In case some of the recordings didn't have a proper calibration, they would appear outside of the "display coords" and additional steps are anyway needed.

We would recommend that you create your custom plot function and adjust the figure as needed.

Here are the refactored code snippets, which are added above:

```matlab
%% Parse display coordinates
edf = Edf2Mat('example.edf');

%% get display coordination events
displayCoordIdxs = cellfun(@(x) contains(x, 'DISPLAY_COORDS'), edf.Events.Messages.info);
displayCoords = obj.Events.Messages.info(displayCoordIdxs);

%% define display range
boundary = struct("minX", floor(min(edf.Samples.posX)), ...
    "minY", floor(min(edf.Samples.posY)), ...
    "maxX", ceil(max(edf.Samples.posX)), ...
    "maxY", ceil(max(edf.Samples.posY)));

if ~isempty(displayCoords)
    parsedCoords = regexp(displayCoords(end), "(?<minX>\d+)\s(?<minY>\d+)\s(?<maxX>\d+)\s(?<maxY>\d+)", "names");
    boundary = structfun(@str2double, parsedCoords{:}, "UniformOutput", false);
end

% result is a struct with the corresponding fields, `display coords` gets prioritized over data points
plotRange = [boundary.minX, boundary.minY, boundary.maxX, boundary.maxY];
disp(boundary);
disp(plotRange);
```

```matlab
%% Filter gaze positions
gazePositions = [edf.Samples.posX, edf.Samples.posY];
inBound = gazePositions(:, 1) >= boundary.minX & gazePositions(:, 1) <= boundary.maxX & ...
          gazePositions(:, 2) >= boundary.minY & gazePositions(:, 2) <= boundary.maxY;

filteredGaze = gazePositions(inBound, :);
```
