### ISSUE TITLE
I got linux support working

### ISSUE THREAD

**Issue by brittyazel** [uzh/edf-converter#2]
Hi, I just wanted to let you know that I modified your script to work perfectly with Linux through wine. I only added a couple of edits to wrap the "ispc" commands in an if statement with all of my modifications made in "isunix" elseifs. I also force useOLDProcedure = true if "isunix' is true for the below to work.

Lastly, the only major change was adding in a command:

```
elseif(isunix)
      command = ['wine', ' ', path, '/private/edf2asc.exe', ' ', '-miss nan -y ']; %britt changed to add wine
end
```
and

```
elseif(isunix)
       [~, obj.output] = system([command obj.filename]);
end
```

and the rest is perfectly working output on Linux. It obviously needs wine to work, but maybe this is worth adding in

**Comment by eydrian** [comment]
Hi, cool thanks, would you mind to create a pull request?

**Comment by brittyazel** [comment]
Yeah no problem, I just want to make a couple quick changes to account for a couple of edge cases. I.e. if they try to run it without Wine installed, etc.

**Comment by eydrian** [comment]
Don't spend to much time on it, I'm anyway thinking of publishing the code for the mex files as well. So maybe it will even be possible to compile it for linux natively in the near future.

**Comment by iandol** [comment]
I've been using edfmex for many moons (which I can compile for macOS, Win and Linux). @eydrian is your linux support now "native"?

**Comment by eydrian** [comment]
Hi @iandol, no it's not. It works through wine.

**Comment by Zahra-M-Aghajan** [comment]
When I run Edf2Mat on file in linux (with wine), I only get two values  for samples (posX, PosY, time) and the function also generates to .asc files with the actual values in it.. is this normal? When I run the function with the sample file provided it works fine, but it doesn't work with my files..
