### ISSUE TITLE
Edf2Mat on Linux

### ISSUE THREAD

**Issue by ozika** [uzh/edf-converter#6]
First of all, thanks for a great toolbox! 

I just have a few comments if anyone else wants to use it on Linux.
1. Correct me if I am wrong but the toolbox seems to rely on edf2asc.exe which is a Windows executable. For that to run on linux, one needs wine installed. 
2. Matlab needs to be run without admin privileges (no sudo). This is a safety feature of wine. 
3. The user running the matlab instance needs to have permissions to read and write the `edf` files. 

Then all works fine :) I just thought that it might be useful to have here.

**Comment by mabiede** [comment]
I added the info to the README (#9). Thanks for sharing it!
