### ISSUE TITLE
Merging EDF files

### ISSUE THREAD

**Issue by DouweHorsthuis** [uzh/edf-converter#7]
Good afternoon,
I was wondering if there is somewhere documentation or an example on how to merge EDF files? 
I want to use the heat map to show where the participant is looking on the screen, but we have 1 EDF for each (1min block). But we have 12 blocks. 

Thank you,
Douwe

**Comment by mabiede** [comment]
@DouweHorsthuis

The heatmap function uses the `Samples` field of the "edf" object.
Loading the other edf files and merging the samples field should return the expected result.

```matlab
% edf 12x1 cell array with all loaded files

combinedEdf = edf{end};
combinedEdf.Samples = cat(1, edf{1:end});
```
